name: '  (FAASR REGISTER)'

on:
  workflow_dispatch:
    inputs:
      workflow_file:
        description: 'Workflow JSON file name'
        required: true
        type: string
        default: 'project1.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pyyaml PyGithub

      - name: Install OpenWhisk CLI
        run: |
          # Download and install the latest OpenWhisk CLI for Linux
          wget -q https://github.com/apache/openwhisk-cli/releases/download/1.2.0/OpenWhisk_CLI-1.2.0-linux-amd64.tgz
          tar -xzf OpenWhisk_CLI-1.2.0-linux-amd64.tgz
          sudo mv wsk /usr/local/bin/wsk
          sudo chmod +x /usr/local/bin/wsk
          # Verify installation
          wsk --help

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Register Functions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_LAMBDA_ROLE_ARN: ${{ secrets.AWS_LAMBDA_ROLE_ARN }}
          OW_API_KEY: ${{ secrets.OW_API_KEY }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          # Run function registration 
          python scripts/register_workflow.py --workflow-file ${{ github.event.inputs.workflow_file }} 
